CREATE TABLE pages (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    content TEXT NOT NULL,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE changes (
    id SERIAL PRIMARY KEY,
    page_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    hash CHAR(64) NOT NULL UNIQUE,
    content TEXT NOT NULL,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY(page_id) REFERENCES pages(id),
    FOREIGN KEY(author_id) REFERENCES users(id)
);

CREATE TABLE links (
    id SERIAL PRIMARY KEY,
    source_id INTEGER NOT NULL,
    dest_slug VARCHAR(255) NOT NULL,

    UNIQUE (source_id, dest_slug),
    FOREIGN KEY(source_id) REFERENCES pages(id)
);

CREATE TABLE logins (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    password_hash CHAR(64) NOT NULL,
    salt CHAR(32) NOT NULL,
    
    FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE sessions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    hash CHAR(64) NOT NULL UNIQUE,
    disposed BOOLEAN DEFAULT FALSE NOT NULL,
    inserted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY(user_id) REFERENCES users(id)
);
