name: leptosfmt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  leptosfmt-analyze:
    name: Run leptosfmt 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install leptosfmt
        run: cargo install leptosfmt

      - name: Run leptosfmt
        run: leptosfmt --check src/**/*.rs
